//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AId { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> PFId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> Zip { get; set; }
    }
}
