//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeoplesEntities : DbContext
    {
        public PeoplesEntities()
            : base("name=PeoplesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Family> Family { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonFamily> PersonFamily { get; set; }
        public virtual DbSet<Telephone> Telephone { get; set; }
    }
}
