//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PId { get; set; }
        public Nullable<int> PFId { get; set; }
        public string Forname { get; set; }
        public string Lastname { get; set; }
    }
}
